Nieuwe Backend
MediSeeUU/MediSeeUU pull request #66
Opened 2022-12-19 11:27 UTC by Koenvisser

Negeer de docstrings en tests, zullen later worden gefixt

2022-12-19 11:36 UTC, elioverhoef commented on backend/API/api/models/common.py
> +    def from_db_value(self, value, expression, connection):
Unused variables: Kunnen weg?

2022-12-19 11:38 UTC, elioverhoef commented on backend/API/api/models/common.py
> +    article48 = "article 4.8",
articles worden nu opgeslagen met punten tussen alles (article 10.3, article 10.8, article 8.3, article 4.8). Moet dat hier aangepast worden?

2022-12-19 11:38 UTC, elioverhoef commented on backend/API/api/models/get_dashboard_columns.py
> +    Args:
Mist docstring details

2022-12-19 11:39 UTC, elioverhoef commented on backend/API/api/models/common.py
> +        name, path, args, kwargs = super().deconstruct()
No docstring. Overal toevoegen?

2022-12-19 11:39 UTC, elioverhoef commented on backend/API/api/models/other/orphan_locks.py
> +        eu_od_number (models.ForeignKey):
Goeie docstring!

2022-12-19 11:41 UTC, elioverhoef commented on backend/API/api/serializers/medicine_serializers/public/common.py
> +    Args:
plz update me

2022-12-19 11:41 UTC, elioverhoef commented on backend/API/api/serializers/medicine_serializers/public/common.py
> +        for related_name, serializer_class, fields in getattr(self.Meta, "any_bools_list"):
I am unreachable! (code is unreachable)

2022-12-19 11:41 UTC, elioverhoef commented on backend/API/api/serializers/medicine_serializers/public/common.py
> +        Selects the items of the specified related history object and inserts it in a flat representation.
Shift me to left !

2022-12-19 11:42 UTC, elioverhoef commented on backend/API/api/serializers/medicine_serializers/public/history.py
> +    HistoryEUOrphanCon,
Moet hier komma?

2022-12-19 11:42 UTC, elioverhoef commented on backend/API/api/serializers/medicine_serializers/public/marketing_authorisation.py
> +    This serializer serializes the :py:class:`.Duration` model.
Add args to comments

2022-12-19 11:43 UTC, elioverhoef commented on backend/API/api/tests/integration_tests/test_views/test_public_medicine.py
> +#     HistoryAuthorisationType,
Moet ik gecomment zijn?

2022-12-19 11:44 UTC, elioverhoef commented on backend/API/api/tests/integration_tests/test_views/test_scraper_urls_view.py
> +#             Group.objects.get(name="anonymous").permissions.add(permission)
Mag ik bestaan?

2022-12-19 11:44 UTC, elioverhoef commented on backend/API/api/tests/integration_tests/test_views/test_update_cache.py
> +#             epar_url="eparurl.com",
Ik wil er ook zijn!

2022-12-19 11:45 UTC, elioverhoef commented on backend/API/api/views/scraper/post/common.py
> +
Hier klopt een aantal docstrings niet, please check met PyCharm

2022-12-19 11:46 UTC, elioverhoef commented on backend/API/api/views/scraper/post/post_human.py
> +    HistoryAuthorisationStatus,
Docstrings: "I require an update!"

2022-12-19 11:47 UTC, elioverhoef commented on backend/API/api/views/scraper/post/post_orphan.py
> +
Do me good

2022-12-19 11:47 UTC, elioverhoef commented on backend/API/api/views/structure_data/orphan_medicine_info.py
> +class Orphan_medicine_info(views.APIView):
Do me an enter

2022-12-19 11:48 UTC, elioverhoef requested changes
Sommige kleine changes required, maar je kan de docstring comments negeren!

2022-12-19 16:00 UTC, elioverhoef approved these changes
C'est formidable!

2022-12-22 14:57 UTC, Yfkesmit commented on backend/API/api/models/get_dashboard_columns.py
> +def insert_extra_dashboard_columns(data, models):
ik vind deze nested for loop nogal intens. Kan dit ook niet mooier met wat list comprehensions oid?

2022-12-22 15:05 UTC, Yfkesmit commented on backend/API/api/serializers/medicine_serializers/public/medicinal_product.py
> +    AnyBoolsList
hier mist komma

2022-12-22 15:06 UTC, Yfkesmit commented on backend/API/api/serializers/medicine_serializers/public/medicinal_product.py
> +            ("procedures", ProceduresSerializer, ["eu_referral", "eu_suspension"]),
hoort de komma achteraan hier wel?

2022-12-22 15:21 UTC, Yfkesmit commented on backend/API/api/tests/unit_tests/test_models/test_common.py
> +#     pass
geen newline aan t einde

2022-12-22 15:26 UTC, Yfkesmit commented on backend/API/api/urls.py
> +    path("structureData/orphanHistories/", OrphanHistoryInfo.as_view()),
moet bij de laatste een komma hier achter? weet niet of dat zomaar kan in een list maar misschien is dit gewoon backend magie

2022-12-22 15:34 UTC, Yfkesmit commented on backend/bat_files/helper/newvenv.bat
> +venv\Scripts\activate
mist newline

2022-12-22 15:35 UTC, Yfkesmit approved these changes

2022-12-22 15:36 UTC, merged