Feature/combiner update mvp
MediSeeUU/MediSeeUU pull request #76
Opened 2023-01-08 13:08 UTC by elioverhoef

**Combiner (& transformer) revamp**
- Attribute changes voor formaat DB
- Bugfixes
- Refactor
- Remove try/catches + add docstrings
- Test data update
- Test data updater (update_test_data.py)
- Remove old unused combiner definitions files
- Changing attribute values in scrapers

2023-01-08 13:35 UTC, miloravi requested changes

2023-01-08 13:35 UTC, miloravi commented on scraping/combiner/attribute_combining_functions.py
> +            # log.warning(f"\"{attr.pdf_file}\" not in the keys of the source: {source_string}")
Horen deze logs gecomment te zijn

2023-01-08 13:35 UTC, miloravi commented on scraping/combiner/attribute_combining_functions.py
> +    """
Hier mist nog een zin als summary aan het begin van de docstring

2023-01-08 13:35 UTC, miloravi commented on scraping/combiner/attribute_combining_functions.py
> +    """
De summaries missen bij  veel toegevoegde docstrings in de file

2023-01-08 13:35 UTC, miloravi commented on scraping/transformer/__main__.py
>      final_json = {}
Wrm wordt hier een empty dict final_json aangemaakt en meegegeven aan get_final_json in plaats van het aan te maken in get_final_json en dan te returnen?

2023-01-08 13:35 UTC, miloravi commented on scraping/utilities/definitions/type_values.py
> -import datetime
Waarom is deze file weggehaald?

2023-01-08 13:35 UTC, miloravi commented on scraping/web_scraper/download.py
> +def get_date_from_url(url:
Enter weghalen

2023-01-08 14:09 UTC, elioverhoef commented on scraping/utilities/definitions/type_values.py
> -import datetime
Werd niet gebruikt, waarden staan in attribute_values

2023-01-08 14:11 UTC, elioverhoef commented on scraping/transformer/__main__.py
>      final_json = {}
Om een JSON waarde te garanderen: Stel json_data["orphan_status"] bestaat niet, dan zou transformer crashen

2023-01-08 14:28 UTC, Koenvisser commented on scraping/combiner/__main__.py
> +        dict[str, any]: Dictionary with sources as keys, and data of sources as attributes
Gebruik Any van de typing module ipv any. any is een functie.

2023-01-08 15:23 UTC, miloravi approved these changes

2023-01-08 21:18 UTC, Koenvisser approved these changes

2023-01-09 08:07 UTC, Kawaii-Killer approved these changes

2023-01-09 08:15 UTC, merged